[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "test_utils"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
k8s-openapi = { workspace = true }
serde_json = { workspace = true }
kube = { version = "0.99", features = ["runtime", "derive"] }
